### PR TITLE
Update docs build configuration

### PR DESCRIPTION
**Pull request by arkid15r**
The following changes update the docs configuration in order to make it buildable again:
    - Use .readthedocs.yaml as a main config file (a coming soon requirement)
    - Update required package list
    - Simplify conf.py
    - Improve/reformat .md files

The latest successful build links:
  - [build run](https://readthedocs.org/projects/refinebio-docs/builds/21157930/)
  - [docs preview](https://refinebio-docs--166.org.readthedocs.build/en/166/)

### CODE REVIEW

**Review by jaclyn-taroni — COMMENTED** [review]
👍🏻  LGTM

My review focused on the Markdown documents' changes and how that translated to the preview.

I'm refraining from approving because I think the reviews from @davidsmejia and @dvenprasad are more critical than mine.

**Review by davidsmejia — APPROVED** [review]
These changes look good to me, please let @dvenprasad take a look before merging. Also could you target the `development` branch

**Review by dvenprasad — COMMENTED** [review]
The layout looks good. The big thing is where's the logo?

One minor thing: 
Screenshot 2023-07-06 at 2 54 24 PM

In the breadcrumb, behind the `/`, there seems to be an invisible link to home of the docs. Text doesn't show up when I try highlight it but the cursor changes when I hover over it. Can we make it visible, please?

**Comment by davidsmejia** [comment]
Ok so I took a closer look at this and I think we should merge this into dev and I can make a new PR to fix the remaining style issues.

**Pull request merged**
