### PR TITLE
separated license into its own file

### PR DESCRIPTION
**Pull request by dvenprasad**
Separated out License information into is own file so we can have flexibility in ordering the Table of Contents.

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
I built this locally and it's doing something strange when I'm on the FAQ page where License comes before FAQ:

Screen Shot 2019-04-17 at 5 58 13 PM

Not sure if this is expected behavior.

**Comment by dvenprasad** [comment]
That is not expected. License is supposed to be last. I built it again, it took away the theme but is rendering content correctly. You're right something very weird is happening. 

Screen Shot 2019-04-18 at 8 56 48 AM

**Comment by jaclyn-taroni** [comment]
Everything else LGTM - should we merge it and see what happens?

**Comment by dvenprasad** [comment]
The actual HTML files are built correctly. Yeah let's merge and see what happens.

**Pull request merged**
